from .py.lgutils import *
from .py.trans import *
from .py.batch_video import *
WEB_DIRECTORY = "web"

NODE_CLASS_MAPPINGS = {
    "GroupExecutorSingle": GroupExecutorSingle,
    "GroupExecutorSender": GroupExecutorSender,
    "GroupExecutorRepeater": GroupExecutorRepeater,
    "LG_ImageSender": LG_ImageSender,
    "LG_ImageReceiver": LG_ImageReceiver,
    "LG_VideoSender": LG_VideoSender,
    "LG_VideoReceiver": LG_VideoReceiver,
    "LG_StringSender": LG_StringSender,
    "LG_StringReceiver": LG_StringReceiver,
    "ImageListSplitter": ImageListSplitter,
    "MaskListSplitter": MaskListSplitter,
    "ImageListRepeater": ImageListRepeater,
    "MaskListRepeater": MaskListRepeater,
    "LG_FastPreview": LG_FastPreview,
    "LG_AccumulatePreview": LG_AccumulatePreview,
    "LG_CreateAndSaveVideo": LG_CreateAndSaveVideo,
    "LG_ConcatVideoFiles": LG_ConcatVideoFiles,
    "LG_SaveAudioGetPath": LG_SaveAudioGetPath,
    "LG_ValueSender": LG_ValueSender,
    "LG_ValueReceiver": LG_ValueReceiver,
    "LG_ClearAccumulatedValues": LG_ClearAccumulatedValues,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "GroupExecutorSingle": "🎈GroupExecutorSingle",
    "GroupExecutorSender": "🎈GroupExecutorSender",
    "GroupExecutorRepeater": "🎈GroupExecutorRepeater",
    "LG_ImageSender": "🎈LG_ImageSender",
    "LG_ImageReceiver": "🎈LG_ImageReceiver",
    "LG_VideoSender": "LG Video Sender",
    "LG_VideoReceiver": "LG Video Receiver",
    "LG_StringSender": "LG String Sender",
    "LG_StringReceiver": "LG String Receiver",
    "ImageListSplitter": "🎈List-Image-Splitter",
    "MaskListSplitter": "🎈List-Mask-Splitter",
    "ImageListRepeater": "🎈List-Image-Repeater",
    "MaskListRepeater": "🎈List-Mask-Repeater",
    "LG_FastPreview": "🎈LG_FastPreview",
    "LG_AccumulatePreview": "🎈LG_AccumulatePreview",
    "LG_CreateAndSaveVideo": "🎈LG_CreateAndSaveVideo",
    "LG_ConcatVideoFiles": "🎈LG_ConcatVideoFiles",
    "LG_SaveAudioGetPath": "🎈LG_SaveAudioGetPath",
    "LG_ValueSender": "🎈LG_ValueSender",
    "LG_ValueReceiver": "🎈LG_ValueReceiver",
    "LG_ClearAccumulatedValues": "🎈LG_ClearAccumulatedValues",
}
